export class Language {
    language = {
        default: {
            "caption_ok"                    : "Ok",
            "caption_app"                   : "App",
            "caption_back"                  : "Back",
            "caption_click"                 : "Click",
            "caption_yes"                   : "Yes",
            "caption_no"                    : "No",
            "caption_submit"                : "Submit",
            "caption_active"                : "Active",
            "caption_inactive"              : "Inactive",
            "caption_expired"               : "Expired",     
            "caption_resume"                : "Resume",
            "caption_renew"                 : "Renew",
            "caption_update"                : "Update",
            "caption_upload"                : "Upload",
            "caption_beta"                  : "Beta",
            "caption_worksheet"             : "Worksheet",
            "caption_workbook"              : "Workbook",
            "caption_betaWorksheet"         : "Beta Worksheet",
            "caption_betaWorkbook"          : "Beta Workbook",
            "caption_desc"                  : "Description",
            "caption_store"                 : "Store",
            "caption_library"               : "Library",
            "caption_betaStore"             : "Beta Store",
            "caption_account"               : "Account",
            "caption_profile"               : "Profile",
            "caption_signup"                : "Signup",
            "caption_subscribe"             : "Subscribe",
            "caption_subscription"          : "Subscription",
            "caption_updateAvail"           : "Update Available",
            "caption_details"               : "Details",
            "caption_viewDetails"           : "View Details",
            "caption_mode"                  : "Mode",
            "caption_lesson"                : "Lesson",
            "caption_quiz"                  : "Quiz",
            "caption_play"                  : "Play",
            "caption_inst"                  : "Instruction",
            "caption_hint"                  : "Hint",
            "caption_explanation"           : "Explanation",
            "caption_flag"                  : "Flag",
            "caption_lock"                  : "Lock",
            "caption_unlock"                : "Unlock",
            "caption_read"                  : "Read",
            "caption_unread"                : "Unread",
            "caption_review"                : "Review",
            "caption_reset"                 : "Reset",
            "caption_exit"                  : "Exit",
            "caption_changePicture"         : "Change Picture",
            "caption_save"                  : "Save",
            "caption_select"                : "Select",
            "caption_start"                 : "Start",
            "caption_settings"              : "Settings",
            "caption_forgotPassword"        : "Forgot Password",
            "caption_signUp"                : "Sign Up",
            "caption_logIn"                 : "Log In",
            "caption_login"                 : "Login",
            "caption_logout"                : "Logout",
            "caption_google"                : "Google",
            "caption_register"              : "Register",
            "caption_sendResetLink"         : "Send Reset Link",
            "caption_getStarted"            : "Get Started",
            "caption_resetPassword"         : "Reset Password",
            "caption_view"                  : "View",
            "caption_getWb"                 : "Get Workbook",
            "caption_seeMore"               : "See more",
            "caption_instShort"             : "Inst",
            "caption_notNow"                : "Not now",
            "caption_chkAns"                : "Check Answer",
            "caption_showAns"               : "Show Answer",
            "caption_close"                 : "Close",
            "caption_summary"               : "Summary",
            "caption_quizSubmittedView"     : "Quiz has been submitted view summary",
        
            "msg_veryficationDone"          : "Your email verification has been done.",
            "msg_confirmNewPassword"        : "Please confirm new password.",
            "msg_allFieldsAreValid"         : "Please make sure all fields are valid.",
            "msg_alreadyAtLastQue"          : "You are already at last question.",
            "msg_alreadyAtFirstQue"         : "You are already at first question.",
            "msg_plsSelectAnOpt"            : "Please select any option.",
            "msg_fillAllBlanks"             : "Please fill all the blank fields.",
            "msg_plsAnsFirst"               : "Please answer first.",
            "msg_useHintFirst"              : "Please use hint first.",
            "msg_unlockFirst"               : "Please unlock first.",
            "msg_plsLoginFirst"             : "Please login first.",
            "msg_plsLockAns"                : "Please lock your answer.",
            "msg_notBetaUSer"               : "You are not a beta user.",
            "msg_passwordInst"              : "Password must be minimum 8 characters, maximum 15 characters, at least one uppercase letter, one lowercase letter, one number and one special character.",
            "msg_oldPasswordReq"            : "Old Password is required.",
            "msg_newPasswordReq"            : "New Password is required.",
            "msg_followPasswordPtrn"        : "Must be follow pattern.",
            "msg_confirmPasswordReq"        : "Confirm Password is required.",
            "msg_updateRequireWb"           : "Update Require please update your workbook.",
            "msg_lessionInfo"               : "Allow to use this worksheet as Lesson or Quiz mode as choice.",
            "msg_plsUnlockAns"              : "Please unlock to change answer.",
            "msg_wsUpdateMsg"               : "You will loose your old worksheet data and response. Do you really want to update?",
            "msg_timeAlertM1"               : "Hurry up...Only ",
            "msg_timeAlertM2"               : " minutes left.",
            "msg_fiveMinLeft"               : "Hurry up...Only 5 min left submit your quiz. Other wise the quiz will automatically submit after time complete.",
            "msg_backBtnMsg"                : "You will lost your response.",
            "msg_learnMcq"                  : "Select an <b class='text-danger'>option</b> to answer. Your answer will <b class='text-danger'>lock-in</b> automatically.<br>To change answer <b class='text-danger'>unlock</b> and then select another option.",
            "msg_learnArrange"              : "Drag items to arrange in the order asked. Click <b class='text-danger'>lock</b> to lock-in your answer.<br>To change your answer <b class='text-danger'>unlock</b> and then rearrange items by dragging. Click <b class='text-danger'>lock</b> to lock-in your answer.",
            "msg_learnFillin"               : "Fill in all the <b class='text-danger'>blanks</b> with appropreate numarical and text value. Click <b class='text-danger'>lock</b> to lock-in your answer.<br>To change your answer <b class='text-danger'>unlock</b> and then change the filled-in values. Click <b class='text-danger'>lock</b> to lock-in your answer.",
            "msg_learnInfo"                 : "Click <b class='text-danger'>Read</b> to mark that you have read this informational content.<br>To mark this content as unread click <b class='text-danger'>Unread</b> button.",

            "text_done"                     : "Done",
            "text_of"                       : "of",
            "text_or"                       : "or",
            "text_info"                     : "Info",
            "text_signUp"                   : "Sign Up",
            "text_google"                   : "Google",
            "text_worksheet"                : "Worksheet",
            "text_workbook"                 : "Workbook",
            "text_worksheets"               : "Worksheets",
            "text_workbooks"                : "Workbooks",
            "text_beta"                     : "beta",
            "text_betaWorksheet"            : "Beta Worksheet",
            "text_betaWorkbook"             : "Beta Workbook",
            "text_desc"                     : "Description",
            "text_subsDetails"              : "Subscription Details",
            "text_userLogin"                : "User Login",
            "text_email"                    : "Email",
            "text_password"                 : "Password",
            "text_fullName"                 : "Full Name",
            "text_country"                  : "Country",
            "text_contact"                  : "Contact",
            "text_doNotHaveAcc"             : "Do not have an account",
            "text_forgetPassword"           : "Forget Password",
            "text_forgotPassword"           : "Forgot Password",
            "text_enterEmailToResetPwd"     : "Enter your email to reset password",
            "text_clickToLogin"             : "Click to login.",
            "text_regNewUser"               : "Register New User",
            "text_resetPassword"            : "Reset Password",
            "text_newPassword"              : "New Password",
            "text_alreadyHaveAcc"           : "Already have an account",
            "text_mode"                     : "Mode",
            "text_lesson"                   : "Lesson",
            "text_quiz"                     : "Quiz",
            "text_suggestedDuration"        : "Suggested Duration",
            "text_selectMode"               : "Select Mode",
            "text_selectTime"               : "Select Time",
            "text_selectedMode"             : "Selected Mode",
            "text_selectedTime"             : "Selected Time",
            "text_selectDuration"           : "Select Duration",
            "text_duration"                 : "Duration",
            "text_min"                      : "Min",
            "text_subsValidity"             : "Subscription validity",
            "text_subsStatus"               : "Subscription status",
            "text_period"                   : "Period",
            "text_endsOn"                   : "Ends on",
            "text_type"                     : "Type",
            "text_days"                     : "Days",
            "text_userEmail"                : "User Email",
            "text_examineerWorkbook"        : "Examineer Workbook",
            "text_congratulation"           : "Congratulations",
            "text_dear"                     : "Dear",
            "text_subscriptions"            : "Subscriptions",
            "text_from"                     : "from",
            "text_userName"                 : "User Name",
            "text_memberSince"              : "Member Since",
            "text_updateDetails"            : "Update Details",
            "text_changePassword"           : "Change Password",
            "text_note"                     : "Note",
            "text_oldPassword"              : "Old Password",
            "text_confirmPassword"          : "Confirm Password",
            "text_summary"                  : "Summary",
            "text_gradedQus"                : "Graded question",
            "text_help"                     : "Help",
            "text_helpUsed"                 : "Help used",
            "text_incorrectAns"             : "Incorrect answer",
            "text_max"                      : "Max",
            "text_score"                    : "Score",
            "text_skipped"                  : "Skipped",
            "text_time"                     : "Time",
            "text_timeTaken"                : "Time taken",
            "text_total"                    : "Total",
            "text_ungradedQus"              : "Ungraded content",
            "text_subscribed"               : "Subscribed",
            "text_level"                    : "Level",
            "text_difficulty"               : "Difficulty",
            "text_language"                 : "Language",
            "text_version"                  : "Version",
            "text_content"                  : "Content",
            "text_noOfWs"                   : "No. of Worksheets",
            "text_relevance"                : "Relevance",
            "text_price"                    : "Price",
            "text_fastPrototyping"          : "Fast Prototyping",
            "text_instruction"              : "Instruction",
            "text_gradingMatrix"            : "Grading Matrix",
            "text_noHelpUsed"               : "No help used",
            "text_hintUsed"                 : "Hint used",
            "text_expUsed"                  : "Explanation used",
            "text_correctScore"             : "Correct Score",
            "text_skipScore"                : "Skip Score",
            "text_incorrectScore"           : "Incorrect Score",
            "text_freeAllowance"            : "Free Allowance",
            "text_item"                     : "Item",
            "text_hint"                     : "Hint",
            "text_explanation"              : "Explanation",
            "text_noOfItems"                : "No. of free items",
            "text_noOfFreeExp"              : "No. of free Explanations",
            "text_noOfFreeHint"             : "No. of free Hints",
            "text_totalSuggestedDur"        : "Suggested duration",
            "text_updateAvail"              : "Update available",
            "text_submitResp"               : "Submit Response",
            "text_attemptedQus"             : "Questions attempted",
            "text_skippedQus"               : "Questions skipped",
            "text_flaggedQus"               : "Questions flagged",
            "text_timeUsed"                 : "Time used",
            "text_totalNoQus"               : "Total content",
            "text_answerStatus"             : "Answer Status",
            "text_youHaveScored"            : "You have scored",
            "text_grade"                    : "Grade",
            "text_correctAnsIs"             : "Correct Answer is",
            "text_correctAns"               : "Correct Answer",
            "text_regToWb"                  : "Register to workbook",
            "text_regToWbMsg1"              : "Register with following details and be the part of examineer.",
            "text_wbContentTxt1"            : "worksheets free",
            "text_wbContentTxt2"            : "free items",
            "text_wbContentTxt3"            : "some hint & explanation free",
            "text_totalTime"                : "min. of material.",
            "text_learnHowTo"               : "Learn how to answer",
            "text_howToAns"                 : "How to answer",

            "title_clock":"Clock",
            "title_useHint":"Use hint",
            "title_useExp":"Use explanation",
            "title_lockAns":"Lock your answer",
            "title_unlockAns":"Unlock your answer",
            "title_flagQus":"Flag this question",
            "title_removeFlag":"Remove flag",
            "title_ansLocked":"Answer is locked",
            "title_qusFlagged":"This question is flagged",
            "title_allItems":"All items",
            "text_pressAnyKey":"Press any key",
            "text_youAreActive":"You are active!",
            "caption_publisher":"Publisher",
            "text_noWbAvail":"No workbook here.",
            "msg_userInactivity":"You have been inactive for sometime. You will be exited from this worksheet shortly."
        }
       
    }
}